apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KCSJhdXRocyI6IHsNCgkJImdoY3IuaW8iOiB7DQogICAgICAgICAgICAiYXV0aCI6ICJkMlZrZEdWeWNqcG5hSEJmZEVkYVZtUm1NMkpXWmtsNWVVVmxkbGt4UzBONGQwcG5UMnRvZFhORU5GVkthRVpTIg0KICAgICAgICB9DQoJfQ0KfQ==
type: kubernetes.io/dockerconfigjson
